"""ARM register data for AArch32 (ARMv7) and AArch64 (ARMv8/v9)."""

REGISTERS = [
    # =========================================================================
    # AArch32 — General Purpose
    # =========================================================================
    {
        "name": "R0",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register. Used as the first function argument and return value in AAPCS.",
        "fields": [],
        "usage_notes": "Caller-saved. Holds the return value after a function call.",
    },
    {
        "name": "R1",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register. Second function argument in AAPCS.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "R2",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register. Third function argument in AAPCS.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "R3",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register. Fourth function argument in AAPCS.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "R4",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register.",
        "fields": [],
        "usage_notes": "Callee-saved. Must be preserved across function calls.",
    },
    {
        "name": "R5",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register.",
        "fields": [],
        "usage_notes": "Callee-saved.",
    },
    {
        "name": "R6",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register.",
        "fields": [],
        "usage_notes": "Callee-saved.",
    },
    {
        "name": "R7",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register. Often used as the frame pointer in Thumb mode.",
        "fields": [],
        "usage_notes": "Callee-saved. Frame pointer in some ABIs.",
    },
    {
        "name": "R8",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register.",
        "fields": [],
        "usage_notes": "Callee-saved.",
    },
    {
        "name": "R9",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register. Platform-specific (sometimes reserved as a static base).",
        "fields": [],
        "usage_notes": "Callee-saved. May be reserved on some platforms.",
    },
    {
        "name": "R10",
        "aliases": [],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register.",
        "fields": [],
        "usage_notes": "Callee-saved.",
    },
    {
        "name": "R11",
        "aliases": ["FP"],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "General-purpose register. Conventionally used as the frame pointer in ARM mode.",
        "fields": [],
        "usage_notes": "Callee-saved. Frame pointer in ARM mode AAPCS.",
    },
    {
        "name": "R12",
        "aliases": ["IP"],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "Intra-procedure-call scratch register.",
        "fields": [],
        "usage_notes": "Caller-saved. Used by the linker as a scratch register for veneers.",
    },
    # =========================================================================
    # AArch32 — Special
    # =========================================================================
    {
        "name": "R13",
        "aliases": ["SP"],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "Stack Pointer. Points to the top of the current stack.",
        "fields": [],
        "usage_notes": "Must be 8-byte aligned at public interfaces. Banked across processor modes.",
    },
    {
        "name": "R14",
        "aliases": ["LR"],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "Link Register. Holds the return address when a BL/BLX instruction is executed.",
        "fields": [],
        "usage_notes": "Caller-saved. Overwritten by subroutine calls.",
    },
    {
        "name": "R15",
        "aliases": ["PC"],
        "architecture": "aarch32",
        "category": "general_purpose",
        "bit_width": 32,
        "description": "Program Counter. Holds the address of the current instruction plus 8 (ARM) or 4 (Thumb).",
        "fields": [],
        "usage_notes": "Reading PC returns current instruction address + 8 in ARM state, +4 in Thumb state.",
    },
    # =========================================================================
    # AArch32 — Status Registers
    # =========================================================================
    {
        "name": "CPSR",
        "aliases": [],
        "architecture": "aarch32",
        "category": "status",
        "bit_width": 32,
        "description": "Current Program Status Register. Contains condition flags, interrupt masks, processor mode, and state bits.",
        "fields": [
            {"bits": "31", "name": "N", "description": "Negative flag"},
            {"bits": "30", "name": "Z", "description": "Zero flag"},
            {"bits": "29", "name": "C", "description": "Carry flag"},
            {"bits": "28", "name": "V", "description": "Overflow flag"},
            {"bits": "27", "name": "Q", "description": "Sticky overflow (saturating arithmetic)"},
            {"bits": "24", "name": "J", "description": "Jazelle state bit"},
            {"bits": "9", "name": "E", "description": "Endianness (0=little, 1=big)"},
            {"bits": "8", "name": "A", "description": "Asynchronous abort mask"},
            {"bits": "7", "name": "I", "description": "IRQ mask"},
            {"bits": "6", "name": "F", "description": "FIQ mask"},
            {"bits": "5", "name": "T", "description": "Thumb state bit (0=ARM, 1=Thumb)"},
            {"bits": "4:0", "name": "M", "description": "Processor mode (e.g. 0x10=User, 0x13=SVC, 0x1F=System)"},
        ],
        "usage_notes": "Condition flags (NZCV) are set by comparison and flag-setting instructions (e.g. CMP, ADDS).",
    },
    {
        "name": "SPSR",
        "aliases": [],
        "architecture": "aarch32",
        "category": "status",
        "bit_width": 32,
        "description": "Saved Program Status Register. Saves a copy of CPSR when an exception occurs.",
        "fields": [
            {"bits": "31:28", "name": "NZCV", "description": "Saved condition flags"},
            {"bits": "7:0", "name": "Control", "description": "Saved interrupt masks and processor mode"},
        ],
        "usage_notes": "Banked per exception mode. Restored to CPSR on exception return.",
    },
    # =========================================================================
    # AArch32 — Floating Point (summary)
    # =========================================================================
    {
        "name": "S0-S31",
        "aliases": [],
        "architecture": "aarch32",
        "category": "floating_point",
        "bit_width": 32,
        "description": "Single-precision floating-point registers. S0-S15 are caller-saved, S16-S31 are callee-saved.",
        "fields": [],
        "usage_notes": "Paired as D0-D15 for double-precision. S0 used for float return values.",
    },
    {
        "name": "D0-D31",
        "aliases": [],
        "architecture": "aarch32",
        "category": "floating_point",
        "bit_width": 64,
        "description": "Double-precision floating-point / NEON registers. D0-D7 are caller-saved, D8-D15 are callee-saved.",
        "fields": [],
        "usage_notes": "D16-D31 available only with Advanced SIMD (NEON). Used for both FP and vector operations.",
    },
    {
        "name": "FPSCR",
        "aliases": [],
        "architecture": "aarch32",
        "category": "floating_point",
        "bit_width": 32,
        "description": "Floating-Point Status and Control Register. Controls rounding mode and holds FP condition flags.",
        "fields": [
            {"bits": "31", "name": "N", "description": "FP negative flag"},
            {"bits": "30", "name": "Z", "description": "FP zero flag"},
            {"bits": "29", "name": "C", "description": "FP carry flag"},
            {"bits": "28", "name": "V", "description": "FP overflow flag"},
            {"bits": "23:22", "name": "RMode", "description": "Rounding mode (00=nearest, 01=+inf, 10=-inf, 11=zero)"},
            {"bits": "25", "name": "DN", "description": "Default NaN mode"},
            {"bits": "24", "name": "FZ", "description": "Flush-to-zero mode"},
        ],
        "usage_notes": "VMRS/VMSR instructions transfer FPSCR to/from ARM registers.",
    },
    # =========================================================================
    # AArch64 — General Purpose
    # =========================================================================
    {
        "name": "X0",
        "aliases": ["W0"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "General-purpose register. First argument and return value in AAPCS64.",
        "fields": [],
        "usage_notes": "Caller-saved. W0 is the lower 32 bits. Writing W0 zero-extends into X0.",
    },
    {
        "name": "X1",
        "aliases": ["W1"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "General-purpose register. Second function argument.",
        "fields": [],
        "usage_notes": "Caller-saved. W1 is the lower 32 bits.",
    },
    {
        "name": "X2",
        "aliases": ["W2"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "General-purpose register. Third function argument.",
        "fields": [],
        "usage_notes": "Caller-saved. W2 is the lower 32 bits.",
    },
    {
        "name": "X3",
        "aliases": ["W3"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "General-purpose register. Fourth function argument.",
        "fields": [],
        "usage_notes": "Caller-saved. W3 is the lower 32 bits.",
    },
    {
        "name": "X4",
        "aliases": ["W4"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "General-purpose register. Fifth function argument.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X5",
        "aliases": ["W5"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "General-purpose register. Sixth function argument.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X6",
        "aliases": ["W6"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "General-purpose register. Seventh function argument.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X7",
        "aliases": ["W7"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "General-purpose register. Eighth function argument.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X8",
        "aliases": ["W8"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Indirect result location register.",
        "fields": [],
        "usage_notes": "Caller-saved. Holds the address of a struct return value when too large for X0.",
    },
    {
        "name": "X9",
        "aliases": ["W9"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Temporary register.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X10",
        "aliases": ["W10"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Temporary register.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X11",
        "aliases": ["W11"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Temporary register.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X12",
        "aliases": ["W12"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Temporary register.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X13",
        "aliases": ["W13"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Temporary register.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X14",
        "aliases": ["W14"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Temporary register.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X15",
        "aliases": ["W15"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Temporary register.",
        "fields": [],
        "usage_notes": "Caller-saved.",
    },
    {
        "name": "X16",
        "aliases": ["W16", "IP0"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "First intra-procedure-call scratch register.",
        "fields": [],
        "usage_notes": "Caller-saved. Used by linker veneers and PLT entries. May be clobbered by branch-through-register.",
    },
    {
        "name": "X17",
        "aliases": ["W17", "IP1"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Second intra-procedure-call scratch register.",
        "fields": [],
        "usage_notes": "Caller-saved. Used by linker veneers alongside X16.",
    },
    {
        "name": "X18",
        "aliases": ["W18", "PR"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Platform register. Reserved on some OSes (e.g., Windows uses it for TEB).",
        "fields": [],
        "usage_notes": "Do not use as a general scratch register. Reserved on Windows, macOS, and some Linux configs.",
    },
    {
        "name": "X19",
        "aliases": ["W19"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Callee-saved register.",
        "fields": [],
        "usage_notes": "Must be preserved across function calls.",
    },
    {
        "name": "X20",
        "aliases": ["W20"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Callee-saved register.",
        "fields": [],
        "usage_notes": "Must be preserved across function calls.",
    },
    {
        "name": "X21",
        "aliases": ["W21"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Callee-saved register.",
        "fields": [],
        "usage_notes": "Must be preserved across function calls.",
    },
    {
        "name": "X22",
        "aliases": ["W22"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Callee-saved register.",
        "fields": [],
        "usage_notes": "Must be preserved across function calls.",
    },
    {
        "name": "X23",
        "aliases": ["W23"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Callee-saved register.",
        "fields": [],
        "usage_notes": "Must be preserved across function calls.",
    },
    {
        "name": "X24",
        "aliases": ["W24"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Callee-saved register.",
        "fields": [],
        "usage_notes": "Must be preserved across function calls.",
    },
    {
        "name": "X25",
        "aliases": ["W25"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Callee-saved register.",
        "fields": [],
        "usage_notes": "Must be preserved across function calls.",
    },
    {
        "name": "X26",
        "aliases": ["W26"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Callee-saved register.",
        "fields": [],
        "usage_notes": "Must be preserved across function calls.",
    },
    {
        "name": "X27",
        "aliases": ["W27"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Callee-saved register.",
        "fields": [],
        "usage_notes": "Must be preserved across function calls.",
    },
    {
        "name": "X28",
        "aliases": ["W28"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Callee-saved register.",
        "fields": [],
        "usage_notes": "Must be preserved across function calls.",
    },
    {
        "name": "X29",
        "aliases": ["W29", "FP"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Frame Pointer. Points to the base of the current stack frame.",
        "fields": [],
        "usage_notes": "Callee-saved. Must be used as FP when frame records are required.",
    },
    {
        "name": "X30",
        "aliases": ["W30", "LR"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Link Register. Holds the return address set by BL/BLR instructions.",
        "fields": [],
        "usage_notes": "Caller-saved. Overwritten by subroutine calls. Use RET to branch to LR.",
    },
    # =========================================================================
    # AArch64 — Special
    # =========================================================================
    {
        "name": "SP",
        "aliases": ["WSP"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Stack Pointer. Points to the top of the current stack. Not a general-purpose register.",
        "fields": [],
        "usage_notes": "Must be 16-byte aligned when used for memory access. Each EL has its own SP.",
    },
    {
        "name": "PC",
        "aliases": [],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Program Counter. Holds the address of the currently executing instruction.",
        "fields": [],
        "usage_notes": "Not directly writable. Updated by branch instructions and exception entry/return.",
    },
    {
        "name": "XZR",
        "aliases": ["WZR"],
        "architecture": "aarch64",
        "category": "general_purpose",
        "bit_width": 64,
        "description": "Zero Register. Always reads as zero; writes are discarded.",
        "fields": [],
        "usage_notes": "Encoded as register 31 (shared with SP — context determines which). WZR is the 32-bit form.",
    },
    # =========================================================================
    # AArch64 — Status / System Registers
    # =========================================================================
    {
        "name": "NZCV",
        "aliases": [],
        "architecture": "aarch64",
        "category": "status",
        "bit_width": 64,
        "description": "Condition flags register. Holds the Negative, Zero, Carry, and Overflow flags.",
        "fields": [
            {"bits": "31", "name": "N", "description": "Negative — set when result is negative (signed)"},
            {"bits": "30", "name": "Z", "description": "Zero — set when result is zero"},
            {"bits": "29", "name": "C", "description": "Carry — set on unsigned overflow or shift carry-out"},
            {"bits": "28", "name": "V", "description": "Overflow — set on signed overflow"},
        ],
        "usage_notes": "Read/written via MSR/MRS instructions. Set by flag-setting instructions (ADDS, SUBS, CMP, etc.).",
    },
    {
        "name": "DAIF",
        "aliases": [],
        "architecture": "aarch64",
        "category": "status",
        "bit_width": 64,
        "description": "Interrupt mask bits register. Controls masking of Debug, SError, IRQ, and FIQ exceptions.",
        "fields": [
            {"bits": "9", "name": "D", "description": "Debug exception mask"},
            {"bits": "8", "name": "A", "description": "SError (asynchronous abort) mask"},
            {"bits": "7", "name": "I", "description": "IRQ mask"},
            {"bits": "6", "name": "F", "description": "FIQ mask"},
        ],
        "usage_notes": "Bits set to 1 = masked (disabled). Use MSR DAIFSet/DAIFClr for atomic modification.",
    },
    {
        "name": "CurrentEL",
        "aliases": [],
        "architecture": "aarch64",
        "category": "status",
        "bit_width": 64,
        "description": "Current Exception Level register. Indicates which EL the processor is executing at.",
        "fields": [
            {"bits": "3:2", "name": "EL", "description": "Exception level (0=EL0/User, 1=EL1/Kernel, 2=EL2/Hypervisor, 3=EL3/Secure Monitor)"},
        ],
        "usage_notes": "Read-only. Use MRS to read. Cannot be written directly.",
    },
    {
        "name": "FPCR",
        "aliases": [],
        "architecture": "aarch64",
        "category": "floating_point",
        "bit_width": 64,
        "description": "Floating-Point Control Register. Controls FP rounding mode, exception traps, and behavior.",
        "fields": [
            {"bits": "25", "name": "DN", "description": "Default NaN mode"},
            {"bits": "24", "name": "FZ", "description": "Flush-to-zero mode"},
            {"bits": "23:22", "name": "RMode", "description": "Rounding mode (00=nearest, 01=+inf, 10=-inf, 11=zero)"},
        ],
        "usage_notes": "Accessed via MRS/MSR. Affects all floating-point and SIMD operations.",
    },
    {
        "name": "FPSR",
        "aliases": [],
        "architecture": "aarch64",
        "category": "floating_point",
        "bit_width": 64,
        "description": "Floating-Point Status Register. Holds cumulative FP exception flags.",
        "fields": [
            {"bits": "31", "name": "N", "description": "FP negative condition flag"},
            {"bits": "30", "name": "Z", "description": "FP zero condition flag"},
            {"bits": "29", "name": "C", "description": "FP carry condition flag"},
            {"bits": "28", "name": "V", "description": "FP overflow condition flag"},
            {"bits": "4", "name": "IDC", "description": "Input denormal cumulative flag"},
            {"bits": "3", "name": "IXC", "description": "Inexact cumulative flag"},
            {"bits": "2", "name": "UFC", "description": "Underflow cumulative flag"},
            {"bits": "1", "name": "OFC", "description": "Overflow cumulative flag"},
            {"bits": "0", "name": "IOC", "description": "Invalid operation cumulative flag"},
        ],
        "usage_notes": "Sticky flags — once set, they remain set until explicitly cleared.",
    },
    # =========================================================================
    # AArch64 — Key System Registers
    # =========================================================================
    {
        "name": "VBAR_EL1",
        "aliases": [],
        "architecture": "aarch64",
        "category": "system",
        "bit_width": 64,
        "description": "Vector Base Address Register (EL1). Holds the base address of the exception vector table for EL1.",
        "fields": [],
        "usage_notes": "Must be 2048-byte aligned (bits [10:0] are RES0). Set during kernel boot.",
    },
    {
        "name": "TTBR0_EL1",
        "aliases": [],
        "architecture": "aarch64",
        "category": "system",
        "bit_width": 64,
        "description": "Translation Table Base Register 0 (EL1). Holds the base address of the page table for the lower virtual address range (user space).",
        "fields": [
            {"bits": "63:48", "name": "ASID", "description": "Address Space Identifier (when TCR_EL1.A1=1)"},
            {"bits": "47:1", "name": "BADDR", "description": "Translation table base address"},
            {"bits": "0", "name": "CnP", "description": "Common not Private (shareable TLB entries between PEs)"},
        ],
        "usage_notes": "Switched on context switch to point to the new process page tables.",
    },
    {
        "name": "SCTLR_EL1",
        "aliases": [],
        "architecture": "aarch64",
        "category": "system",
        "bit_width": 64,
        "description": "System Control Register (EL1). Controls MMU enable, caches, alignment checking, and endianness at EL1.",
        "fields": [
            {"bits": "0", "name": "M", "description": "MMU enable (0=disabled, 1=enabled)"},
            {"bits": "2", "name": "C", "description": "Data cache enable"},
            {"bits": "12", "name": "I", "description": "Instruction cache enable"},
            {"bits": "1", "name": "A", "description": "Alignment check enable"},
            {"bits": "25", "name": "EE", "description": "Exception endianness (0=little, 1=big)"},
        ],
        "usage_notes": "Critical for boot. Typically M, C, and I are set early to enable MMU and caches.",
    },
]
